### ISSUE TITLE
custom data issue: inputs querying incorrect table

### ISSUE THREAD

**Issue by declann** [alexkreidler/mosaic-playground#1]
Hi!

Really liking mocking something up using this playground!

I'm using custom data, so I have no `data` object in JSON spec and instead upload a file and give it a name, and then use that name in my `from` fields in JSON spec.

It seems like this works for my marks, but not for my inputs - it looks like despite using `from: X` the query is to a table with example data in it (in this case, from the crossfilter example, which I had loaded before I started to edit)

![image](https://github.com/user-attachments/assets/7bff0b75-96cb-4876-bcad-37f6835a8d2e)

Any ideas about what might cause this type of confusion? Perhaps something became inconsistent on Mosaic side if nothing obvious in Playground side?

Can supply a testcase if needed.

Thanks a lot for making and sharing this neat project!

Declan

**Comment by alexkreidler** [comment]
I can't seem to reproduce this right away. When I upload this [example CSV](https://gist.githubusercontent.com/alexkreidler/4a1effb7f81929faa853e3423702f0a4/raw/7f522d8e2eccf03ac0ac89cf5cb9dd295ab15701/cars.csv) and name it the `cars` table, I can modify the crossfilter example to delete the data field, and change the fields to use the `Displacement` and `Horsepower` to get this chart:
![mosaic-chart(30)](https://github.com/user-attachments/assets/7654e4a5-f4a4-4d38-ac85-c6229e79dba2)

```json
{
  "params": {
    "brush": {
      "select": "crossfilter"
    }
  },
  "vconcat": [
    {
      "plot": [
        {
          "mark": "rectY",
          "data": {
            "from": "cars",
            "filterBy": "$brush"
          },
          "x": {
            "bin": "Displacement"
          },
          "y": {
            "count": ""
          },
          "fill": "steelblue",
          "insetLeft": 0.5,
          "insetRight": 0.5
        },
        {
          "select": "intervalX",
          "as": "$brush"
        }
      ],
      "xDomain": "Fixed",
      "xLabel": "Displacement",
      "xLabelAnchor": "center",
      "yTickFormat": "s",
      "height": 200
    },
    {
      "plot": [
        {
          "mark": "rectY",
          "data": {
            "from": "cars",
            "filterBy": "$brush"
          },
          "x": {
            "bin": "Horsepower"
          },
          "y": {
            "count": ""
          },
          "fill": "steelblue",
          "insetLeft": 0.5,
          "insetRight": 0.5
        },
        {
          "select": "intervalX",
          "as": "$brush"
        }
      ],
      "xDomain": "Fixed",
      "xLabel": "Horsepower",
      "xLabelAnchor": "center",
      "yTickFormat": "s",
      "height": 200
    }
  ]
}
```

If you could provide a test dataset and Mosaic spec I could look into it a bit more.

**Comment by declann** [comment]
Thanks for checking!

No issue when I try with a CSV file - my issue was with an Arrow file. I think that file may be corrupted or inconsistent, as I also had issues with it in other tools, and moved to a CSV. Old data fields appearing made me think there was a bug here, apologies!
