### ISSUE TITLE
image download button only picks first plot

### ISSUE THREAD

**Issue by declann** [alexkreidler/mosaic-playground#2]
e.g., in the crossfilter example:

![image](https://github.com/user-attachments/assets/8fc82211-278d-4d88-9127-a28a4a9d1b63)

Clicking the image button takes this png:

![mosaic-chart (1)](https://github.com/user-attachments/assets/31782e95-a5c8-4acd-8e1a-00e385537e59)

Which misses the second plot

**Comment by alexkreidler** [comment]
Now it outputs this image:
![mosaic-chart](https://github.com/user-attachments/assets/152cda7e-f8c5-4f5d-b649-262de81e8239)

**Comment by declann** [comment]
Cool, thanks!
