### ISSUE TITLE
can't replace uploaded data

### ISSUE THREAD

**Issue by declann** [alexkreidler/mosaic-playground#3]
When I've uploaded data that a spec is using, sometimes it's useful to replace that data and see updated visuals. This doesn't seem to work whenever I make a new upload, delete old one, and set the new upload table name = to the old one (I guess that the table already exists and isn't dropped, or similar)

![image](https://github.com/user-attachments/assets/423756d6-04d4-409a-8d0f-dc8f35938723)

I had a look at the code and making this work might be a bit elaborate due to duckdb-wasm-kit providing a convenient [insertFile](https://github.com/holdenmatt/duckdb-wasm-kit/blob/main/src/files/insertFile.ts) and not `replaceFile` or `insertOrReplaceFile`

**Comment by alexkreidler** [comment]
Should be fixed now! Thanks for your issue reports and for using this app, sorry it took me a bit to get around to this!
